### ISSUE TITLE
Explained? Yeah

### ISSUE THREAD

**Issue by kenshin2202** [StethoSaysHello/KikBruteForcer#2]
Why would anyone pay to set proxy chains up or to redirect captchas? Do you have any idea how they work? 
E: Who in their right minds would use a captcha solving service when they can redirect the captcha itself? Stfu with this retarded shit skid

**Comment by StethoSaysHello** [comment]
Why would someone open multiple false issues on a post not even meant for you?
"Redirect capatchas"? Either you direct it to a solving service, which costs money, or you don't solve them and don't get in. You can't just bypass them for free. 

And yes, you can use your own VPN/proxychain, that doesn't solve the issue if it literally taking lifetimes to crack a password. 
If you go at a single account in multiple sessions/chains even, Kik itself will start closing connections.

**Comment by kenshin2202** [comment]
Yeah 'you can't solve them for free' clears everything. Learn to code <3

Proxychain and vpn are hella diff and you straight up called bruteforcing a username 'bullshit'. Kik doesn't close connections either. You obv don't know what you talking about here so go learn something first. You can bruteforce smtp with proxychains and a list so shut up with this nonsense bullshit about kik connections of all things

**Comment by StethoSaysHello** [comment]
Kik DOES close connections, seriously, try it yourself. Don't wait for login authorization or run multiple sessions on the same account, and voila, closed connections. 

Yes, I'm calling people who say they can brute force Kik liars because they are. I'm very aware that VPNs and proxychains are entirely different things, but neither will do anything to fix the fact that it will take multiple lifetimes to brute force an account.
